### ISSUE TITLE
TypeError: must assign a string

### ISSUE THREAD

**Issue by Stefouch** [Varriount/fvtt-autopublish#10]
I have this error with my autopublish script and I don't understand why as I think I have everything set up correctly.

See failed job for error log:

https://github.com/fvtt-fria-ligan/yearzero-combat-fvtt/actions/runs/3864394734/jobs/6587147004

Do you have an idea why it throws that error ?

**Comment by Varriount** [comment]
I made a PR which I think will fix things - it appears that some of the version fields in your manifest are integers, not strings. I've also released a fix which should prevent the problem in the future.
