### ISSUE TITLE
Recommending new release

### ISSUE THREAD

**Issue by dmdorman** [Varriount/fvtt-autopublish#12]
Hey, thanks for making this tool!

I just tried to do a release, and my repo's autopublish GitHub action failed. Looks like Foundry has changed how releases are done. I noticed you've already updated the code for this change, but when I looked at the source code for the new release, it still used the old code. I was able to get the GitHub action working in my fork simply by creating a new release.

I believe if you spin a new release it will resolve the issues for anybody else running into this issue.

Thanks again!

**Comment by Varriount** [comment]
Ok, I've published a new release. Would it be possible for you to check whether the changes have spread to your repository?

**Comment by dmdorman** [comment]
worked great as shown by https://github.com/dmdorman/hero6e-foundryvtt/actions/runs/7883070487/job/21509357527 succeeding

Thanks!
