### ISSUE TITLE
KeyError: 'changelog'

### ISSUE THREAD

**Issue by akrigline** [Varriount/fvtt-autopublish#3]
[Failed Run](https://github.com/League-of-Foundry-Developers/fvtt-advanced-macros/runs/2770167799?check_suite_focus=true)

[Configuration File](https://github.com/League-of-Foundry-Developers/fvtt-advanced-macros/blob/main/.github/workflows/main.yml)

I hoped that by explicitly providing `changelog-url` it would bypass the need for a changelog in the manifest, which isn't strictly necessary.

**Comment by Varriount** [comment]
@akrigline I believe this is fixed, but can you confirm?

**Comment by akrigline** [comment]
Was a new version released? (not seeing it in the release list)

**Comment by Varriount** [comment]
A new tag was made a while ago (v1.0.2a), however I just published a new release as well (v1.0.3a)
