### ISSUE TITLE
minimumCoreVersion error

### ISSUE THREAD

**Issue by MrVauxs** [Varriount/fvtt-autopublish#9]
https://github.com/MrVauxs/pf2e-jb2a-macros/actions/runs/3027624111/jobs/4871884844

Looks like it's not (fully) V10 compatible?

**Comment by Stefouch** [comment]
I have the same error here:

https://github.com/fvtt-fria-ligan/blade-runner-foundry-vtt/actions/runs/3619645965/jobs/6100931012

`minimumCoreVersion` is deprecated in Foundry, and replaced with `compatibility.minimum`

**Comment by Varriount** [comment]
Sorry for the delay - I accidentally unsubscribed myself from activity notifications for my repositories.

This should be fixed in the latest version, at least when reading data from manifest files. I'm still mulling over the best way to handle data from command-line arguments.
